apiVersion: v1
kind: Service
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: solar-system
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: siddharth67/solar-system:v6
        imagePullPolicy: Always
        name: solar-system
        ports:
        - containerPort: 80
